version: '3.8'

services:
  # Nginx API Gateway
  nginx-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api-routes.conf:/etc/nginx/conf.d/api-routes.conf:ro
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - api-net

  # Servizio Users
  user-service:
    build: ../services/user-service
    environment:
      PORT: 3000
      DB_URL: postgresql://users_db_user:password@user-db:5432/users_db
    depends_on:
      - user-db
    networks:
      - api-net
    deploy:
      replicas: 2

  user-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: users_db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - api-net

  # Servizio Products (multiple replicas)
  product-service:
    build: ../services/product-service
    environment:
      PORT: 3000
      REDIS_URL: redis://product-cache:6379
    depends_on:
      - product-cache
    networks:
      - api-net
    deploy:
      replicas: 3

  product-cache:
    image: redis:7-alpine
    networks:
      - api-net

  # Servizio Orders
  order-service:
    build: ../services/order-service
    environment:
      PORT: 3000
      MONGO_URL: mongodb://order-db:27017/orders
    depends_on:
      - order-db
    networks:
      - api-net
    deploy:
      replicas: 2

  order-db:
    image: mongo:6
    volumes:
      - order_db_data:/data/db
    networks:
      - api-net

volumes:
  user_db_data:
  order_db_data:

networks:
  api-net:
    driver: bridge
