# Usa un'immagine base ufficiale di Nginx
FROM nginx:latest

# Copia un file index.html personalizzato nella directory di default di Nginx
COPY index.html /usr/share/nginx/html

# Esponi la porta 80 (la porta standard per HTTP)
EXPOSE 80
