groups:
  - name: microservices.rules
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up{job=~".*-service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for {{ $labels.job }}"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }}s for {{ $labels.job }}"

      # Database Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: MongoDBDown
        expr: up{job="mongodb"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MongoDB is down"
          description: "MongoDB database has been down for more than 1 minute."

      - alert: ElasticsearchDown
        expr: up{job="elasticsearch"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Elasticsearch is down"
          description: "Elasticsearch has been down for more than 1 minute."

      - alert: ClickHouseDown
        expr: up{job="clickhouse"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "ClickHouse is down"
          description: "ClickHouse has been down for more than 1 minute."

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute."

      # Resource Alerts
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of its memory limit"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} CPU"

      # Kafka Alerts
      - alert: KafkaDown
        expr: up{job="kafka"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka is down"
          description: "Kafka broker has been down for more than 1 minute."

      - alert: KafkaConnectDown
        expr: up{job="kafka-connect"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka Connect is down"
          description: "Kafka Connect has been down for more than 1 minute."

      - alert: HighKafkaLag
        expr: kafka_consumer_lag_sum > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Kafka consumer lag"
          description: "Kafka consumer lag is {{ $value }} messages"

      # Business Logic Alerts
      - alert: HighOrderFailureRate
        expr: rate(orders_failed_total[5m]) / rate(orders_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High order failure rate"
          description: "Order failure rate is {{ $value | humanizePercentage }}"

      - alert: LowUserRegistrations
        expr: rate(user_registrations_total[1h]) < 1
        for: 15m
        labels:
          severity: info
        annotations:
          summary: "Low user registration rate"
          description: "User registration rate is {{ $value }} per hour"

      - alert: DatabaseConnectionPoolExhaustion
        expr: db_connections_active / db_connections_max > 0.9
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database connection pool is {{ $value | humanizePercentage }} full"

  - name: infrastructure.rules
    rules:
      # Disk Space Alerts
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk space is low"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.device }}"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space is critically low"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.device }}"

      # Network Alerts
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High network traffic"
          description: "Network traffic is {{ $value | humanize }}B/s on {{ $labels.device }}"

  - name: data-consistency.rules
    rules:
      # Event Sourcing Alerts
      - alert: EventStoreDown
        expr: up{job="eventstore"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "EventStore is down"
          description: "EventStore has been down for more than 1 minute."

      - alert: EventProcessingLag
        expr: event_processing_lag_seconds > 60
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High event processing lag"
          description: "Event processing lag is {{ $value }}s"

      - alert: ProjectionBuildFailure
        expr: increase(projection_build_failures_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Projection build failure"
          description: "{{ $value }} projection build failures in the last 5 minutes"

      # Data Sync Alerts
      - alert: DataSyncFailure
        expr: increase(data_sync_failures_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Data synchronization failure"
          description: "{{ $value }} data sync failures in the last 5 minutes"

      - alert: StaleReadModel
        expr: time() - read_model_last_updated_timestamp > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Stale read model detected"
          description: "Read model {{ $labels.model }} hasn't been updated for {{ $value }}s"
