# Elasticsearch Configuration for Catalog Service
# Optimized for microservices catalog and search functionality

# Cluster Configuration
cluster.name: catalog-cluster
node.name: catalog-node

# Network Configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Configuration
discovery.type: single-node
cluster.initial_master_nodes: ["catalog-node"]

# Path Configuration
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory and Performance
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 30%
indices.memory.min_index_buffer_size: 96mb

# Index Configuration
indices.fielddata.cache.size: 40%
indices.requests.cache.size: 2%
indices.queries.cache.size: 10%

# Circuit Breaker Configuration
indices.breaker.total.limit: 95%
indices.breaker.request.limit: 60%
indices.breaker.fielddata.limit: 40%

# Thread Pool Configuration
thread_pool:
  write:
    size: 8
    queue_size: 10000
  search:
    size: 13
    queue_size: 10000
  get:
    size: 8
    queue_size: 1000

# Index Management
action.auto_create_index: true
action.destructive_requires_name: true

# Logging Configuration
logger.level: INFO
logger.org.elasticsearch.discovery: DEBUG

# Security Configuration (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring Configuration
xpack.monitoring.collection.enabled: true
xpack.monitoring.exporters:
  local:
    type: local
    use_ingest: false

# Machine Learning (disabled to save resources)
xpack.ml.enabled: false

# Watcher (disabled to save resources)
xpack.watcher.enabled: false

# Index Lifecycle Management
xpack.ilm.enabled: true

# Snapshots Configuration
path.repo: ["/usr/share/elasticsearch/snapshots"]

# Allocation Awareness (for single node setup)
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# Indexing Configuration
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 1s
index.max_result_window: 100000

# Search Configuration
search.max_buckets: 65536
search.default_search_timeout: 60s

# Bulk Configuration
bulk.udp.enabled: false
