# Dynamic configuration
http:
  # Middlewares
  middlewares:
    # CORS middleware
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Security headers
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        isDevelopment: false

    # Rate limiting
    api-ratelimit:
      rateLimit:
        burst: 100
        period: 1m

    # Compression
    compression:
      compress: {}

    # Circuit breaker
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.3 || ResponseCodeRatio(500, 600, 0, 600) > 0.3"
        checkPeriod: 10s
        fallbackDuration: 30s
        recoveryDuration: 10s

    # Retry middleware
    retry:
      retry:
        attempts: 3
        initialInterval: 100ms

  # Services
  services:
    # Health check service
    health-check:
      loadBalancer:
        servers:
          - url: "http://traefik:8080/ping"

  # Routers
  routers:
    # API Health check
    health:
      rule: "Path(`/health`)"
      service: health-check
      middlewares:
        - cors

    # Catch-all for API documentation
    api-docs:
      rule: "PathPrefix(`/docs`)"
      service: api@internal
      middlewares:
        - cors
        - security-headers

# TLS configuration
tls:
  certificates: []

# TCP services (if needed)
tcp:
  services: {}
  routers: {}
